name: ActServe Investment App Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for PostgreSQL to be ready
      run: |
        sudo apt-get update && sudo apt-get install -y wait-for-it
        wait-for-it localhost:5432 --timeout=15 --strict -- echo "Postgres is up and running"

    - name: Run Tests
      env:
        SECRET_KEY: "vc+zftrhwgt9)e82a@h7m3ur%e5!w+34yr$6_sgd%yyqqsd@p&"
        DEBUG: False
        DB_NAME: ${{ env.POSTGRES_DB }}
        DB_USER: ${{ env.POSTGRES_USER }}
        DB_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        DB_HOST: postgres
        DB_PORT: 5432
      run: |
        python manage.py test investments.tests